#!/usr/bin/env bash
# FizzBuzz

for ((n = 1; n <= 100; ++n))
do
    if ((n % 3 && n % 5))
    then
        echo $n
    else
        (( n % 3 )) || echo -n "Fizz"
        (( n % 5 )) || echo -n "Buzz"
        echo
    fi
done
